name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java_version: [21]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.2
      - name: Build with Gradle
        run: ./gradlew build
